services:
  zapret-v2ray-docker:
    container_name: zapret-v2ray-docker
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
        DNSCRYPT_DIR: ${DNSCRYPT_DIR}
        V2RAY_DIR: ${V2RAY_DIR}
        ZAPRET_DIR: ${ZAPRET_DIR}
        _CONFIGS_DIR_INT: ${_CONFIGS_DIR_INT}
        _LOGS_DIR_INT: ${_LOGS_DIR_INT}

    stdin_open: true

    # For iptables (zapret)
    cap_add:
      - NET_ADMIN
      - NET_RAW

    # V2Ray
    ports:
      - ${V2RAY_PORTS}
      - ${V2RAY_PORTS_2}
      - ${V2RAY_PORTS_3}
      - ${V2RAY_PORTS_4}
      - ${V2RAY_PORTS_5}

    # Config and log files
    volumes:
      - "${DNSCRYPT_CONFIG_FILE}:${_CONFIGS_DIR_INT}/dnscrypt-proxy.toml"
      - "${V2RAY_CONFIG_FILE}:${_CONFIGS_DIR_INT}/v2ray.json"
      - "${ZAPRET_CONFIG_FILE}:${_CONFIGS_DIR_INT}/zapret.conf"
      - "${LOGS_DIR}:${_LOGS_DIR_INT}"
